### PR TITLE
Address review follow-ups on the UIComponent refactor (#350)

### PR DESCRIPTION
**Pull request by jvanderaa**
## What this is

Follow-up review fixes on top of the merged #350 UI Component Framework refactor, targeting the `u/pavan-uicomponents-easy-kc` integration branch (not `develop`). #350 moved the detail views to the declarative framework and dropped the custom `*_retrieve.html` templates — good direction. This PR addresses one functional regression plus several cleanups our review flagged, and adds regression test coverage.

All changes are in `nautobot_circuit_maintenance/views.py` and `nautobot_circuit_maintenance/tests/test_views.py`.

### 1. Fix: `validate_source` no longer 500s on OAuth sources (the one blocker)
`Source.test_authentication()` deliberately re-raises `RedirectAuthorize` (`sources.py`) for OAuth sources (e.g. Gmail) that need to send the user through the provider consent flow. After the refactor, `validate_source` only caught `(AttributeError, TypeError, ValueError)`, so `RedirectAuthorize` escaped as an unhandled 500 — and the "Validate Authentication" button links straight to this action, so it was user-reachable.

`validate_source` now:
- Catches `RedirectAuthorize` and redirects to the OAuth authorize URL (restores pre-refactor behavior).
- Catches `ValueError` and **logs it** with `exc_info=True` (the refactor had dropped the logging).
- Attaches a Django `messages` flash (success/error) and **redirects back to the object detail view**, instead of `render()`-ing the legacy `notificationsource.html` template with three hand-built empty tables.

Why redirect-with-messages instead of the direct `render()`:
- It's the idiomatic pattern for a POST/GET action that reports a result, and it lets the detail page render via the UI framework rather than the legacy backward-compat template.
- It removes the "Temporary fix to pass test cases" scaffolding (the empty `ContactAssociationTable([])` / `DynamicGroupTable([])` / `ObjectMetadataTable([])`).
- Note: the previous implementation also supported a `return_url` GET param and redirected to it directly. I intentionally did **not** restore that — redirecting to a user-supplied URL is an open-redirect risk. We always redirect to the object's own detail page.

### 2. Cleanup: remove dead `CustomMaintenanceFieldsPanel`
This panel only existed to compute `data["notification_provider"]`, which is written but never read anywhere (no template or field references it). Replaced its single usage with a plain `ObjectFieldsPanel(fields="__all__")` and removed the now-unused `get_obj_from_context` import. No behavior change.

### 3. Cleanup: remove duplicated class attributes in `RawNotificationUIViewSet`
`serializer_class`, `table_class`, and `action_buttons` were each declared twice (once above `object_detail_content`, once below). Removed the redundant second block.

### 4. Cleanup + logging: `NotificationObjectFieldsPanel.get_data`
- Narrowed `except (AttributeError, TypeError, ValueError)` to `except ValueError` (what `Source.init()` actually raises) so unrelated bugs aren't masked, and added a `logger.warning(..., exc_info=True)` on the failure path.
- Dropped the defensive `try/except` around `instance.providers.all()` (a plain reverse manager access that doesn't raise those exceptions).
- Added a comment explaining that `account` / `source_type` / `providers_display` are runtime-only pseudo-fields attached to the instance for display.

### 5. Tests
- Updated `test_validate_view_ok` / `test_validate_view_ko` to assert the new redirect-and-flash behavior (302 to the detail view + the message in the messages framework) instead of a 200 render.
- Added `test_validate_view_redirect_authorize` — the regression test for the OAuth path: a source that raises `RedirectAuthorize` now redirects to `google_authorize` instead of erroring.
- Extracted the repeated permission-granting setup into a small `_grant_view_permission()` helper.

## Not included (flagging for discussion)
- No new changelog fragment: this all rolls up under the existing `changes/350.housekeeping` for the UIComponent effort, and the target is the integration branch, so a second fragment would just create a duplicate release-notes line.
- The legacy `notificationsource.html` template is now unused by the validate flow. I left it in place to keep this PR scoped to the regression + cleanups; we can remove it in the branch's eventual develop merge (it already carries a "3.0 TODO: remove" comment).

## Test evidence
- `invoke unittest --label nautobot_circuit_maintenance.tests.test_views` → `Ran 179 tests ... OK (skipped=29)`.
- `NotificationSourceTest` (verbose) → `Ran 24 tests ... OK (skipped=4)`, including `test_validate_view_ok`, `test_validate_view_ko`, and the new `test_validate_view_redirect_authorize`.
- `ruff check` / `ruff format --check` clean on both changed files.

### CODE REVIEW

**Comment by jvanderaa** [comment]
Superseded by #395, which re-homes this work onto `develop`.

The blocker here was not the changes in this PR — it was the base branch. `u/pavan-uicomponents-easy-kc` pins `nautobot = ">=2.4.16,<3.0.0"` and was cut before Nautobot 3.0 shipped, so its CI `stable` legs now fail at import with `ImportError: cannot import name 'PluginCustomValidator'` (renamed to `CustomValidator` in Nautobot 3) in `custom_validators.py` and `template_content.py` — files untouched by either this PR or #350. Since Nautobot 2 support lives on `ltm-2.4` and `develop`/`main` are Nautobot 3 only, there was no reason to keep the work on a 2.4-era base.

#395 carries all of these fixes plus the Nautobot 3 adaptations, and picked up one additional real bug in the process: the ParsedNotification `ObjectsTablePanel` badge link pointed at a nonexistent `parsednotification_list` route, which Nautobot 3 catches via `test_body_content_table_list_url`.

Closing in favor of #395.
